Add: The length of the simulation (number of hours in a period) can be switched between 'year', 'month' and 'week'. Corresponding changes have been made throughout the project.
NextStep:
With the pyo.Piecewise function, the error "AttributeError: 'ConcreteModel' object has no attribute 'Piecewise_Fragility[1,1].DCC_lambda'" needed to be fixed. Otherwise, manually write the codes to achieve the same feature to the Piecewise function.